service: default
runtime: python37

handlers:
- url: /static
  static_dir: static/
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

 # Instances that don't pass this check are not added to the pool.
readiness_check:
  path: "/"  # A 200 OK indicates success
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300  # For new deployments, failures here will result in a roll back

includes:
  # Create this file with `gcloud kms decrypt --location global --keyring tech4nature --key hogapp --ciphertext-file env_variables.yaml.encrypted --plaintext-file env_variables.yaml
  - env_variables.yaml
