dist: bionic
language: python
python:
- '3.6'
env:
  global:
    - DB_USER=postgres
    - DB_PASS=
    - DJANGO_SECRET_KEY=kjaslj
    - AWS_SECRET_ACCESS_KEY=asdq3ad
    - GOOGLE_MAP_API_KEY=asdasd
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
    - gdal-bin
    - libproj-dev
    - libgeos-dev
    - libspatialite-dev
    - ffmpeg
before_script:
  - psql -U postgres -c "create extension postgis"
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database hog_test;' -U postgres
script:
- cd hog && python manage.py test --settings=hog.test_settings
notifications:
  email:
  - seb.bacon@gmail.com
