language: python
python:
- '3.6'
env:
  global:
    - DB_USER=postgres
    - DB_PASS=
    - DJANGO_SECRET_KEY=kjaslj
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -U postgres -c "create extension postgis"
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database hog_test;' -U postgres
script:
- cd hog && python manage.py test
notifications:
  email:
  - seb.bacon@gmail.com
