# Generated by Django 2.1.7 on 2019-03-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('software_version', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hog',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('weight', 'weight'), ('temp', 'temp')], db_index=True, max_length=10)),
                ('measurement', models.FloatField()),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Box')),
                ('hog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Hog')),
            ],
        ),
    ]
