# Generated by Django 2.1.7 on 2019-03-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20190317_1718")]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="measurement",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
