# Generated by Django 2.1.7 on 2019-06-09 15:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190325_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
