# Generated by Django 2.1.7 on 2019-06-17 08:49

from django.db import migrations


class Migration(migrations.Migration):
    """Drop unnecessary indexes
    """

    dependencies = [("api", "0006_location_coords")]

    operations = [
        migrations.RunSQL("DROP INDEX api_measurement_hog_id_9ceb3008_like;"),
        migrations.RunSQL("DROP INDEX api_measurement_location_id_49898f98_like;"),
        migrations.RunSQL("DROP INDEX api_measurement_measurement_type_59708cff_like;"),
        migrations.RunSQL("DROP INDEX api_location_location_type_96e54784_like"),
        migrations.RunSQL("DROP INDEX api_hog_code_684801e3_like"),
    ]
