# Generated by Django 2.1.7 on 2019-06-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190618_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='hog',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
