# Generated by Django 2.2.2 on 2019-08-30 09:22

from django.db import migrations, models
from api.models import Measurement
from api.models import set_ordering_token


def set_default_ordering(apps, schema_editor):
    for m in Measurement.objects.all():
        set_ordering_token(m)


class Migration(migrations.Migration):

    dependencies = [("api", "0009_auto_20190620_0817")]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="ordering_token",
            field=models.TextField(db_index=True, default="1"),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_ordering),
    ]
