# Generated by Django 2.2.2 on 2019-08-30 10:44

from django.db import migrations
from api.models import Measurement
from api.models import set_ordering_token


def set_default_ordering(apps, schema_editor):
    for m in Measurement.objects.all():
        set_ordering_token(None, m, None, None, None, None)


class Migration(migrations.Migration):
    """This migration is to update the ordering fields following a change of format
    """

    dependencies = [("api", "0010_measurement_ordering_token")]

    operations = [migrations.RunPython(set_default_ordering)]
