# Generated by Django 2.2.2 on 2019-10-18 10:47

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190830_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Republic',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('box', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
