# Generated by Django 2.2.2 on 2019-10-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('api', '0012_republic'),
    ]

    operations = [
        migrations.AddField(
            model_name='republic',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
            preserve_default=False,
        ),
    ]
